services:
  db18:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo18
      - POSTGRES_PASSWORD=odoo18
    ports:
      - "5434:5432"        # Host port changed to 5434 for Odoo 18 database
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data
    networks:
      - dokploy-network-odoo
      - dokploy-network

  odoo18:
    image: odoo:18.0
    depends_on:
      - db18
    ports:
      - "8070:8069"        # Host port changed to 8070 for Odoo 18
    environment:
      - HOST=db18
      - PORT=5432          # Docker service internal port
      - USER=odoo18
      - PASSWORD=odoo18
    volumes:
      - odoo18-web-data:/var/lib/odoo
    networks:
      - dokploy-network-odoo
      - dokploy-network
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo18.entrypoints=websecure"
      - "traefik.http.routers.odoo18.rule=Host(`${ODOO18_HOST}`)"
      - "traefik.http.routers.odoo18.tls.certresolver=letsencrypt"
      - "traefik.http.services.odoo18.loadbalancer.server.port=8070"

volumes:
  odoo18-db-data:
  odoo18-web-data:

networks:
  dokploy-network-odoo:
    external: true
  dokploy-network:
    external: true
